"use server";
import { Types } from "mongoose";
import { requireSalerSession } from "@/lib/auth/require-saler";
import Commande from "@/lib/models/Commande";
import { Tenant, User } from "@/lib/models/User";
import Store from "@/lib/models/Store";
import Annee from "@/lib/models/Annee";
import type { ActionResult } from "@/lib/utils/action-result";

export async function generateInvoice(commandId:string):Promise<ActionResult<{buffer:number[];filename:string}>>{try{const context=await requireSalerSession();if(!Types.ObjectId.isValid(commandId))return{success:false,message:"Facture invalide."};const sale=await Commande.findOne({_id:commandId,tenantId:context.tenantId,shopId:context.storeId}).populate("clientId","name phone email matricule").lean();if(!sale)return{success:false,message:"Vente introuvable."};const[tenant,store,annee,saler]=await Promise.all([Tenant.findById(context.tenantId).select("designation logo telephone email").lean(),Store.findById(context.storeId).select("designation reference coordonnes").lean(),Annee.findById(sale.anneeId).select("slug").lean(),User.findById(context.userId).select("pseudo matricule").lean()]);const pdfMake=(await import("pdfmake/build/pdfmake")).default;const body:any[]=[["Produit","Qte","Prix","Reduction","Total"],...sale.commandes.map(l=>[`${l.designation}${l.code?` (${l.code})`:""}`,l.qte,`${l.unitPrice} ${l.currency}`,`${l.reduction}%`,`${l.total} ${l.currency}`])];const doc:any={content:[{text:tenant?.designation??"ELMES-TEKA",style:"header"},{text:`Facture ${sale.reference}`,style:"title"},{text:`Boutique: ${store?.designation??""} | Exercice: ${annee?.slug??""}`},{text:`Vendeur: ${saler?.pseudo??""} (${saler?.matricule??""})`},{text:`Client: ${(sale.clientId as any)?.name??""} - ${(sale.clientId as any)?.phone??""}`},{table:{headerRows:1,widths:["*",40,70,60,70],body},margin:[0,15,0,10]},{text:`Sous-total: ${sale.subtotal} ${sale.currency}`,alignment:"right"},{text:`Reduction: ${sale.discountAmount} ${sale.currency}`,alignment:"right"},{text:`Total: ${sale.totalAmount} ${sale.currency}`,bold:true,alignment:"right"},{text:"Merci pour votre confiance.",margin:[0,25,0,0],alignment:"center"}],styles:{header:{fontSize:18,bold:true},title:{fontSize:15,bold:true,margin:[0,10,0,10]}}};const buffer=await pdfMake.createPdf(doc).getBuffer();return{success:true,message:"Facture generee.",data:{buffer:Array.from(buffer),filename:`facture-${sale.reference}.pdf`}};}catch(error:any){return{success:false,message:error.message||"Erreur generation facture."};}}
