"use client";
import { useEffect, useState } from "react";
import Pusher from "pusher-js";
import { BellIcon, CloseIcon } from "@/icons";
import { Dropdown } from "@/components/ui/dropdown/Dropdown";
import { useAdminShell } from "@/context/AdminShellContext";
import { getTenantSupplyRequests, reviewSupplyRequest } from "@/actions/workspace.actions";

export default function NotificationDropdown(){const{account}=useAdminShell();const[open,setOpen]=useState(false);const[items,setItems]=useState<any[]>([]);const load=async()=>{if(account.type!=="TENANT")return;const r=await getTenantSupplyRequests();if(r.success)setItems(r.data)};useEffect(()=>{load();const key=process.env.NEXT_PUBLIC_PUSHER_KEY;const cluster=process.env.NEXT_PUBLIC_PUSHER_CLUSTER;if(!key||!cluster||!account.tenantId)return;const p=new Pusher(key,{cluster,channelAuthorization:{endpoint:"/api/pusher/auth",transport:"ajax"}});const channels=["stocks","commandes","depenses"].map(resource=>p.subscribe(`private-tenant-${account.tenantId}-${resource}`));channels.forEach(channel=>channel.bind_global(()=>load()));return()=>{p.disconnect()}},[account.tenantId,account.type]);const decide=async(id:string,decision:"APPROVED"|"REJECTED")=>{await reviewSupplyRequest(id,decision);await load()};return <div className="relative"><button onClick={()=>setOpen(!open)} className="relative flex h-11 w-11 items-center justify-center rounded-full border border-gray-200 bg-white text-gray-500 dark:border-gray-800 dark:bg-gray-900"><BellIcon/>{items.length>0&&<span className="absolute right-0 top-0 h-2.5 w-2.5 rounded-full bg-error-500"/>}</button><Dropdown isOpen={open} onClose={()=>setOpen(false)} className="absolute right-0 mt-3 flex max-h-[480px] w-[360px] flex-col overflow-y-auto rounded-2xl border bg-white p-3 shadow-theme-lg dark:border-gray-800 dark:bg-gray-900"><div className="flex items-center justify-between border-b pb-3"><h5 className="font-semibold">Demandes d’approvisionnement</h5><button onClick={()=>setOpen(false)}><CloseIcon/></button></div>{items.length===0?<p className="p-6 text-center text-sm text-gray-500">Aucune demande en attente.</p>:items.map(item=><div key={item.id} className="border-b p-3 text-sm dark:border-gray-800"><b>{item.reference}</b><p>{item.store} - {item.productCount} produit(s)</p><div className="mt-2 flex gap-2"><button onClick={()=>decide(item.id,"APPROVED")} className="rounded-lg bg-success-500 px-3 py-1.5 text-xs text-white">Valider</button><button onClick={()=>decide(item.id,"REJECTED")} className="rounded-lg bg-error-500 px-3 py-1.5 text-xs text-white">Rejeter</button></div></div>)}</Dropdown></div>}
